blog:integration-test
Melaku05/blog pull request #8
Opened 2022-07-26 04:00 UTC by Melaku05

# Project requirements
## Make sure that the N+1 problem is solved when fetching all posts and their comments for a user. 
## Integration specs
- User index page
- user show page
- User post index page
- Post show page

2022-07-26 09:16 UTC, DammyShittu requested changes
Hi team,

## Highlights
✔️ Use of capybara for testing features
✔️ All written tests are passing

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Required Changes ♻️
_Check the comments under the review._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-07-26 09:16 UTC, DammyShittu commented on spec/integration/users_index_spec.rb
> +    end
- [ ] For the user index page you are missing the test that redirects to the user's show page when you click on a user. Kindly include that.

2022-07-26 09:16 UTC, DammyShittu commented on spec/integration/users_show_spec.rb
> +end
- [ ] For the user show page you are missing the test that asserts you can see the user's first 3 posts. Kindly include that as well

2022-07-26 09:16 UTC, DammyShittu commented on spec/integration/posts_index_spec.rb
> +    end
- [ ] For the posts index you are missing the following tests:

  * Tests that asserts you can see how many comments a post has.
  * Tests that asserts you can see how many likes a post has.

2022-07-26 09:16 UTC, DammyShittu commented on spec/integration/posts_show_spec.rb
> +    end
- [ ] For the post show page you are missing the test that asserts you can see the post title.

2022-07-27 14:56 UTC, Lordkaito approved these changes
Hi @Melaku05, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-07-27 16:11 UTC, merged